# Generated by Django 5.0 on 2025-08-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='image',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Processed image after deblurring. Can be null if processing is incomplete.', null=True, upload_to='after_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='before_image',
            field=models.ImageField(help_text='Original image before processing. This field is required.', upload_to='before_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_deblurred',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the image was successfully deblurred. Null if not processed yet.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='distortion_type',
            field=models.CharField(blank=True, choices=[('Low Quality', 'Low Quality'), ('Horizontal Blur', 'Horizontal Blur'), ('Vertical Blur', 'Vertical Blur'), ('Low Light', 'Low Light')], help_text='Type of distortion detected in the image. Can be null if not analyzed yet.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='plate_no',
            field=models.CharField(blank=True, help_text='License plate number extracted from the image. Can be null if not detected.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Failed', 'Failed')], help_text='Processing status. Can be null for pending/in-progress items.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this image. Can be null for anonymous uploads.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.user'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user'], name='core_image_user_id_4dcf4d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['status'], name='core_image_status_bca4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='core_image_created_47d1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['date_deblurred'], name='core_image_date_de_029c3a_idx'),
        ),
    ]
