# Generated by Django 5.0 on 2025-08-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_image_options_alter_image_after_image_and_more'),
        ('core', '0003_add_admin'),
    ]

    operations = [
    ]
