# Generated by Django 5.0 on 2025-08-18 13:01

import django.db.models.deletion
from django.db import migrations, models

def create_default_admin(apps, schema_editor):
    Admin = apps.get_model("core", "Admin")
    Admin.objects.create(
        first_name="Default",
        last_name="Admin",
        email="admin@lipad.com",
        password="lipad-admin"  
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]


