# Generated by Django 5.0 on 2025-08-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250819_2035'),
        ('core', '0005_add_admin_02'),
    ]

    operations = [
    ]
