# Generated by Django 5.0 on 2025-08-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0004_merge_20250819_2035_0005_add_admin_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this image. Can be null for anonymous uploads.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.user'),
        ),
    ]
