# Generated by Django 5.0 on 2025-08-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded this image. Can be null for anonymous uploads.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.user'),
        ),
    ]
