# Generated by Django 4.2 on 2025-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_image_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="after_distortion_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low Quality", "Low Quality"),
                    ("Horizontal Blur", "Horizontal Blur"),
                    ("Vertical Blur", "Vertical Blur"),
                    ("Low Light", "Low Light"),
                    ("Normal", "Normal"),
                ],
                help_text="Type of distortion detected in the image. Can be null if not analyzed yet.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="conf_score",
            field=models.CharField(
                blank=True,
                help_text="Confidence score for the detected license plate number. Can be null if not detected.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="distortion_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low Quality", "Low Quality"),
                    ("Horizontal Blur", "Horizontal Blur"),
                    ("Vertical Blur", "Vertical Blur"),
                    ("Low Light", "Low Light"),
                    ("Normal", "Normal"),
                ],
                help_text="Type of distortion detected in the image. Can be null if not analyzed yet.",
                max_length=20,
                null=True,
            ),
        ),
    ]
