# Generated by Django 4.2 on 2025-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_image_after_distortion_type_image_conf_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="date_uploaded",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the image was successfully uploaded. Null if not processed yet.",
                null=True,
            ),
        ),
    ]
