# Generated by Django 4.2 on 2025-09-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_image_date_uploaded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="date_uploaded",
        ),
    ]
