# Generated by Django 4.2 on 2025-09-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_image_date_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='session_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='after_distortion_type',
            field=models.CharField(blank=True, choices=[('Low Quality', 'Low Quality'), ('Horizontal Blur', 'Horizontal Blur'), ('Vertical Blur', 'Vertical Blur'), ('Low Light', 'Low Light'), ('Normal', 'Normal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Processed image after enhancement', null=True, upload_to='secure_uploads/after/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='before_image',
            field=models.ImageField(help_text='Original image before processing', upload_to='secure_uploads/before/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='conf_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_deblurred',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='distortion_type',
            field=models.CharField(blank=True, choices=[('Low Quality', 'Low Quality'), ('Horizontal Blur', 'Horizontal Blur'), ('Vertical Blur', 'Vertical Blur'), ('Low Light', 'Low Light'), ('Normal', 'Normal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='plate_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Processing', 'Processing')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.user'),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='core_admin',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
